### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liamxg** [edonnachie/oecd-health#1]
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found

**Comment by edonnachie** [comment]
This seems to indicate a font problem on MasOS. Try removing the reference to Lato in the theme() funcion, or replace it with a font that is installed on your system (e.g. Garamond).

See:

https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon

**Comment by liamxg** [comment]
thanks for your help, very appreciated that.
